import java.util.Scanner;

public class ErrorsAndExceptions {
    /*
        Errors
            - sytatical
                Int a
             - logical errors
                - Exceptions - try/catch
                - multiple catches
                - finally block
                - unavoidable errors - stack memory overflow
     */

//    public static void main(String[] arg) {
//        int i = 10;
//        int numerator;
//        int denominator;
//        Scanner input = new Scanner(System.in);
//
//        while(true) {
//            try {
//                System.out.println("Enter Numerator: ");
//                numerator = input.nextInt();
//
//                System.out.println("Enter denominator: ");
//                denominator = input.nextInt();
//
////                var file = new File('xyz.txt')
//
//                System.out.println("Division: " + (numerator/denominator));
//            } catch(ArithmeticException e) {
//                System.out.println("ArithmeticException  occurred!");
//                e.printStackTrace();
//            } catch(Exception e) {
//                System.out.println("Generic Exception  occurred!");
//                e.printStackTrace();
//            } finally {
////                file = null;
//                System.out.println("I got result!");
//            }
//        }
//    }
}
